baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "harta.xyz" # the base hostname & protocol for your site.

paginate: 6 #articles per page
paginate_path: /blog/page:num #makes pagination working

# header text
title: GISMan blog
header: Harta dhe GIS

# for welcome page
# to replace image go to index.html
email:
  address: "diskmanti@yahoo.co.uk"
  text: "diskmanti (at) yahoo (dot) co (dot) uk"

# disqus comment
disqus:
    shortname: "gismanblog" #your disqus comment short name

# google analytics
google:
    tracking-id: "UA-77148426-1" #your tracking id here

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"

permalink: /posts/:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
